/*
 * @fileoverview Medical lab knowledge base - the foundation of the local
 * (no-API) extraction engine. Covers ~75 analytes across the panels that
 * appear on Indian and US lab reports (CBC, LFT, KFT, lipid, thyroid,
 * diabetes, vitamins, electrolytes, iron studies, cardiac, coagulation).
 *
 * Each analyte defines:
 *  - aliases:   every spelling/abbreviation labs actually print (matched
 *               with hard word boundaries so "AST" never matches "fASTing")
 *  - unit:      the display unit used when the report omits one
 *  - range:     fallback adult reference range, used ONLY when the report
 *               does not print its own range ({ low, high } - either side
 *               may be null for one-sided ranges like "< 200")
 *  - sanity:    hard plausibility bounds; values outside are OCR noise and
 *               are rejected (prevents grabbing dates, IDs, phone numbers)
 *  - scale:     true for cell counts where "7.5 x10^3" style units must be
 *               normalized to absolute counts
 *  - notes:     optional human phrasing used by the local insights engine
 */

function A(key, name, category, aliases, unit, range, sanity, extra = {}) {
  return { key, name, category, aliases, unit, range, sanity, ...extra };
}

const ANALYTES = [
  // ---------- Lipid Panel ----------
  A('cholesterol_total', 'Total Cholesterol', 'Lipid Panel',
    ['total cholesterol', 'cholesterol total', 'cholesterol, total', 'serum cholesterol', 'cholesterol'],
    'mg/dL', { low: null, high: 200 }, { min: 50, max: 600 },
    { notes: { high: 'raises cardiovascular risk; diet, exercise and sometimes medication help bring it down' } }),
  A('hdl', 'HDL Cholesterol', 'Lipid Panel',
    ['hdl cholesterol', 'hdl-c', 'hdl'],
    'mg/dL', { low: 40, high: null }, { min: 10, max: 150 },
    { notes: { low: 'is the "good" cholesterol - regular aerobic exercise is the most reliable way to raise it' } }),
  A('ldl', 'LDL Cholesterol', 'Lipid Panel',
    ['ldl cholesterol calculated', 'ldl cholesterol, calculated', 'ldl cholesterol', 'ldl-c', 'ldl'],
    'mg/dL', { low: null, high: 100 }, { min: 10, max: 400 },
    { notes: { high: 'is the "bad" cholesterol most tied to artery plaque buildup' } }),
  A('vldl', 'VLDL Cholesterol', 'Lipid Panel',
    ['vldl cholesterol calculated', 'vldl cholesterol', 'vldl'],
    'mg/dL', { low: 5, high: 40 }, { min: 1, max: 150 }),
  A('non_hdl', 'Non-HDL Cholesterol', 'Lipid Panel',
    ['non-hdl cholesterol', 'non hdl cholesterol', 'non-hdl'],
    'mg/dL', { low: null, high: 130 }, { min: 20, max: 500 }),
  A('triglycerides', 'Triglycerides', 'Lipid Panel',
    ['triglycerides', 'triglyceride', 'serum triglycerides'],
    'mg/dL', { low: null, high: 150 }, { min: 20, max: 2000 },
    { notes: { high: 'often responds well to cutting sugar/refined carbs and alcohol' } }),
  A('chol_hdl_ratio', 'Cholesterol/HDL Ratio', 'Lipid Panel',
    ['cholesterol/hdl ratio', 'chol/hdl ratio', 'tc/hdl ratio', 'tc/hdl'],
    'ratio', { low: null, high: 4.5 }, { min: 1, max: 15 }),
  A('lpa', 'Lipoprotein(a)', 'Lipid Panel',
    ['lipoprotein(a)', 'lipoprotein (a)', 'lp(a)', 'lp (a)'],
    'mg/dL', { low: null, high: 30 }, { min: 0, max: 300 }),
  A('apob', 'Apolipoprotein B', 'Lipid Panel',
    ['apolipoprotein b', 'apo b', 'apo-b', 'apob'],
    'mg/dL', { low: null, high: 100 }, { min: 20, max: 300 }),

  // ---------- Diabetes ----------
  A('glucose_fasting', 'Glucose (Fasting)', 'Diabetes',
    ['fasting blood sugar', 'fasting blood glucose', 'fasting plasma glucose', 'glucose fasting', 'glucose, fasting', 'glucose - fasting', 'fasting glucose', 'fbs', 'fpg'],
    'mg/dL', { low: 70, high: 99 }, { min: 20, max: 800 },
    { notes: { high: 'in the 100-125 range suggests prediabetes; 126+ suggests diabetes', low: 'can cause dizziness and shakiness (hypoglycemia)' } }),
  A('glucose_pp', 'Glucose (Post-Prandial)', 'Diabetes',
    ['post prandial blood sugar', 'postprandial blood sugar', 'post prandial glucose', 'glucose post prandial', 'glucose pp', 'ppbs', 'pp blood sugar', 'glucose (pp)', '2 hour post prandial'],
    'mg/dL', { low: 70, high: 140 }, { min: 20, max: 800 }),
  A('glucose_random', 'Glucose (Random)', 'Diabetes',
    ['random blood sugar', 'random blood glucose', 'random glucose', 'glucose random', 'rbs', 'blood sugar', 'blood glucose', 'glucose'],
    'mg/dL', { low: 70, high: 140 }, { min: 20, max: 800 }),
  A('hba1c', 'Hemoglobin A1c', 'Diabetes',
    ['hemoglobin a1c', 'glycosylated hemoglobin', 'glycated hemoglobin', 'glyco hb', 'hba1c', 'hb a1c', 'a1c'],
    '%', { low: 4, high: 5.6 }, { min: 3, max: 20 },
    { notes: { high: '5.7-6.4% suggests prediabetes; 6.5%+ suggests diabetes. It reflects ~3 months of average blood sugar' } }),
  A('eag', 'Estimated Average Glucose', 'Diabetes',
    ['estimated average glucose', 'eag'],
    'mg/dL', { low: 70, high: 117 }, { min: 50, max: 500 }),
  A('insulin_fasting', 'Insulin (Fasting)', 'Diabetes',
    ['fasting insulin', 'insulin fasting', 'insulin, fasting', 'serum insulin', 'insulin'],
    'µIU/mL', { low: 2, high: 25 }, { min: 0.1, max: 300 }),

  // ---------- Complete Blood Count ----------
  A('hemoglobin', 'Hemoglobin', 'Complete Blood Count',
    ['haemoglobin', 'hemoglobin', 'hgb', 'hb'],
    'g/dL', { low: 12, high: 17 }, { min: 2, max: 25 },
    { notes: { low: 'suggests anemia - iron-rich foods help, but the cause should be identified' } }),
  A('rbc', 'Red Blood Cell Count', 'Complete Blood Count',
    ['red blood cell count', 'rbc count', 'total rbc', 'rbc'],
    'million/cumm', { low: 4.0, high: 5.8 }, { min: 1, max: 9 }),
  A('wbc', 'White Blood Cell Count', 'Complete Blood Count',
    ['white blood cell count', 'total leucocyte count', 'total leukocyte count', 'wbc count', 'tlc', 'wbc', 'leucocyte count', 'leukocyte count'],
    '/cumm', { low: 4000, high: 11000 }, { min: 300, max: 300000 },
    { scale: true, notes: { high: 'often reflects infection or inflammation', low: 'can mean reduced immunity - worth discussing with a doctor' } }),
  A('platelets', 'Platelet Count', 'Complete Blood Count',
    ['platelet count', 'platelets', 'plt'],
    '/cumm', { low: 150000, high: 450000 }, { min: 5000, max: 2000000 },
    { scale: true, notes: { low: 'affects clotting; very low values need prompt medical attention' } }),
  A('hematocrit', 'Hematocrit', 'Complete Blood Count',
    ['haematocrit', 'hematocrit', 'packed cell volume', 'pcv', 'hct'],
    '%', { low: 36, high: 50 }, { min: 10, max: 70 }),
  A('mcv', 'MCV', 'Complete Blood Count',
    ['mean corpuscular volume', 'mcv'],
    'fL', { low: 80, high: 100 }, { min: 40, max: 150 }),
  A('mch', 'MCH', 'Complete Blood Count',
    ['mean corpuscular hemoglobin', 'mch'],
    'pg', { low: 27, high: 33 }, { min: 10, max: 50 }),
  A('mchc', 'MCHC', 'Complete Blood Count',
    ['mean corpuscular hemoglobin concentration', 'mchc'],
    'g/dL', { low: 32, high: 36 }, { min: 20, max: 45 }),
  A('rdw', 'RDW', 'Complete Blood Count',
    ['red cell distribution width', 'rdw-cv', 'rdw'],
    '%', { low: 11.5, high: 14.5 }, { min: 8, max: 35 }),
  A('mpv', 'MPV', 'Complete Blood Count',
    ['mean platelet volume', 'mpv'],
    'fL', { low: 7.5, high: 11.5 }, { min: 4, max: 20 }),
  A('neutrophils_pct', 'Neutrophils', 'Complete Blood Count',
    ['neutrophils', 'neutrophil', 'polymorphs', 'neut'],
    '%', { low: 40, high: 70 }, { min: 0, max: 100 }, { siblingAbs: 'neutrophils_abs' }),
  A('lymphocytes_pct', 'Lymphocytes', 'Complete Blood Count',
    ['lymphocytes', 'lymphocyte', 'lymph'],
    '%', { low: 20, high: 40 }, { min: 0, max: 100 }, { siblingAbs: 'lymphocytes_abs' }),
  A('monocytes_pct', 'Monocytes', 'Complete Blood Count',
    ['monocytes', 'monocyte', 'mono'],
    '%', { low: 2, high: 10 }, { min: 0, max: 100 }, { siblingAbs: 'monocytes_abs' }),
  A('eosinophils_pct', 'Eosinophils', 'Complete Blood Count',
    ['eosinophils', 'eosinophil', 'eos'],
    '%', { low: 1, high: 6 }, { min: 0, max: 100 }, { siblingAbs: 'eosinophils_abs' }),
  A('basophils_pct', 'Basophils', 'Complete Blood Count',
    ['basophils', 'basophil', 'baso'],
    '%', { low: 0, high: 2 }, { min: 0, max: 100 }, { siblingAbs: 'basophils_abs' }),
  A('neutrophils_abs', 'Absolute Neutrophil Count', 'Complete Blood Count',
    ['absolute neutrophil count', 'absolute neutrophils', 'anc'],
    '/cumm', { low: 2000, high: 7000 }, { min: 100, max: 50000 }, { scale: true }),
  A('lymphocytes_abs', 'Absolute Lymphocyte Count', 'Complete Blood Count',
    ['absolute lymphocyte count', 'absolute lymphocytes', 'alc'],
    '/cumm', { low: 1000, high: 3000 }, { min: 100, max: 50000 }, { scale: true }),
  A('monocytes_abs', 'Absolute Monocyte Count', 'Complete Blood Count',
    ['absolute monocyte count', 'absolute monocytes', 'amc'],
    '/cumm', { low: 200, high: 1000 }, { min: 10, max: 20000 }, { scale: true }),
  A('eosinophils_abs', 'Absolute Eosinophil Count', 'Complete Blood Count',
    ['absolute eosinophil count', 'absolute eosinophils', 'aec'],
    '/cumm', { low: 20, high: 500 }, { min: 0, max: 20000 }, { scale: true }),
  A('basophils_abs', 'Absolute Basophil Count', 'Complete Blood Count',
    ['absolute basophil count', 'absolute basophils', 'abc'],
    '/cumm', { low: 0, high: 100 }, { min: 0, max: 5000 }, { scale: true }),
  A('esr', 'ESR', 'Complete Blood Count',
    ['erythrocyte sedimentation rate', 'esr'],
    'mm/hr', { low: 0, high: 20 }, { min: 0, max: 150 }),
  A('reticulocytes', 'Reticulocyte Count', 'Complete Blood Count',
    ['reticulocyte count', 'reticulocytes', 'retic count'],
    '%', { low: 0.5, high: 2.5 }, { min: 0, max: 25 }),

  // ---------- Liver Function ----------
  A('bilirubin_total', 'Bilirubin (Total)', 'Liver Function',
    ['total bilirubin', 'bilirubin total', 'bilirubin, total', 'bilirubin (total)', 'bilirubin'],
    'mg/dL', { low: 0.3, high: 1.2 }, { min: 0, max: 40 }),
  A('bilirubin_direct', 'Bilirubin (Direct)', 'Liver Function',
    ['direct bilirubin', 'bilirubin direct', 'bilirubin, direct', 'conjugated bilirubin'],
    'mg/dL', { low: null, high: 0.3 }, { min: 0, max: 30 }),
  A('bilirubin_indirect', 'Bilirubin (Indirect)', 'Liver Function',
    ['indirect bilirubin', 'bilirubin indirect', 'unconjugated bilirubin'],
    'mg/dL', { low: 0.2, high: 1.0 }, { min: 0, max: 30 }),
  A('ast', 'AST (SGOT)', 'Liver Function',
    ['aspartate aminotransferase', 'sgot', 'ast (sgot)', 'ast/sgot', 'ast'],
    'U/L', { low: 5, high: 40 }, { min: 1, max: 5000 },
    { notes: { high: 'is a liver enzyme; mild elevations are common and often reversible (alcohol, meds, fatty liver)' } }),
  A('alt', 'ALT (SGPT)', 'Liver Function',
    ['alanine aminotransferase', 'sgpt', 'alt (sgpt)', 'alt/sgpt', 'alt'],
    'U/L', { low: 5, high: 45 }, { min: 1, max: 5000 },
    { notes: { high: 'is the most liver-specific enzyme; weight management and avoiding alcohol usually help' } }),
  A('alp', 'Alkaline Phosphatase', 'Liver Function',
    ['alkaline phosphatase', 'alk phos', 'alp'],
    'U/L', { low: 40, high: 130 }, { min: 5, max: 2000 }),
  A('ggt', 'GGT', 'Liver Function',
    ['gamma glutamyl transferase', 'gamma gt', 'ggtp', 'ggt'],
    'U/L', { low: 5, high: 55 }, { min: 1, max: 3000 }),
  A('total_protein', 'Total Protein', 'Liver Function',
    ['total protein', 'protein total', 'protein, total', 'serum protein'],
    'g/dL', { low: 6.0, high: 8.3 }, { min: 2, max: 15 }),
  A('albumin', 'Albumin', 'Liver Function',
    ['albumin', 'serum albumin'],
    'g/dL', { low: 3.5, high: 5.2 }, { min: 1, max: 8 }),
  A('globulin', 'Globulin', 'Liver Function',
    ['globulin', 'serum globulin'],
    'g/dL', { low: 2.0, high: 3.5 }, { min: 0.5, max: 8 }),
  A('ag_ratio', 'A/G Ratio', 'Liver Function',
    ['a/g ratio', 'a:g ratio', 'albumin/globulin ratio', 'albumin globulin ratio'],
    'ratio', { low: 1.0, high: 2.2 }, { min: 0.2, max: 5 }),
  A('ldh', 'LDH', 'Liver Function',
    ['lactate dehydrogenase', 'ldh'],
    'U/L', { low: 140, high: 280 }, { min: 50, max: 5000 }),

  // ---------- Kidney Function ----------
  A('urea', 'Urea', 'Kidney Function',
    ['blood urea', 'urea'],
    'mg/dL', { low: 15, high: 40 }, { min: 3, max: 400 }),
  A('bun', 'BUN', 'Kidney Function',
    ['blood urea nitrogen', 'bun'],
    'mg/dL', { low: 7, high: 20 }, { min: 1, max: 200 }),
  A('creatinine', 'Creatinine', 'Kidney Function',
    ['serum creatinine', 'creatinine'],
    'mg/dL', { low: 0.6, high: 1.3 }, { min: 0.1, max: 25 },
    { notes: { high: 'reflects kidney filtration; hydration status and muscle mass also affect it' } }),
  A('uric_acid', 'Uric Acid', 'Kidney Function',
    ['uric acid', 'serum uric acid'],
    'mg/dL', { low: 3.5, high: 7.2 }, { min: 1, max: 20 },
    { notes: { high: 'can lead to gout; limiting red meat, seafood and alcohol helps' } }),
  A('egfr', 'eGFR', 'Kidney Function',
    ['estimated glomerular filtration rate', 'egfr', 'gfr'],
    'mL/min/1.73m²', { low: 60, high: null }, { min: 1, max: 200 }),

  // ---------- Electrolytes & Minerals ----------
  A('sodium', 'Sodium', 'Electrolytes',
    ['serum sodium', 'sodium', 'na+'],
    'mEq/L', { low: 136, high: 145 }, { min: 100, max: 180 }),
  A('potassium', 'Potassium', 'Electrolytes',
    ['serum potassium', 'potassium', 'k+'],
    'mEq/L', { low: 3.5, high: 5.1 }, { min: 1.5, max: 9 }),
  A('chloride', 'Chloride', 'Electrolytes',
    ['serum chloride', 'chloride', 'cl-'],
    'mEq/L', { low: 98, high: 107 }, { min: 70, max: 140 }),
  A('bicarbonate', 'Bicarbonate', 'Electrolytes',
    ['bicarbonate', 'hco3', 'co2'],
    'mEq/L', { low: 22, high: 29 }, { min: 5, max: 45 }),
  A('calcium', 'Calcium', 'Electrolytes',
    ['serum calcium', 'calcium total', 'calcium, total', 'calcium'],
    'mg/dL', { low: 8.5, high: 10.5 }, { min: 4, max: 18 }),
  A('phosphorus', 'Phosphorus', 'Electrolytes',
    ['phosphorus', 'phosphorous', 'phosphate'],
    'mg/dL', { low: 2.5, high: 4.5 }, { min: 0.5, max: 12 }),
  A('magnesium', 'Magnesium', 'Electrolytes',
    ['serum magnesium', 'magnesium', 'mg++'],
    'mg/dL', { low: 1.7, high: 2.4 }, { min: 0.5, max: 8 }),

  // ---------- Thyroid ----------
  A('tsh', 'TSH', 'Thyroid',
    ['thyroid stimulating hormone', 'ultrasensitive tsh', 'tsh ultrasensitive', 'tsh'],
    'µIU/mL', { low: 0.4, high: 4.5 }, { min: 0.01, max: 150 },
    { notes: { high: 'suggests an underactive thyroid (hypothyroidism)', low: 'suggests an overactive thyroid (hyperthyroidism)' } }),
  A('t3_total', 'T3 (Total)', 'Thyroid',
    ['total t3', 't3 total', 't3, total', 'triiodothyronine', 't3'],
    'ng/dL', { low: 80, high: 200 }, { min: 10, max: 800 }),
  A('t4_total', 'T4 (Total)', 'Thyroid',
    ['total t4', 't4 total', 't4, total', 'thyroxine', 't4'],
    'µg/dL', { low: 5, high: 12 }, { min: 0.5, max: 30 }),
  A('ft3', 'Free T3', 'Thyroid',
    ['free t3', 'ft3', 'free triiodothyronine'],
    'pg/mL', { low: 2.3, high: 4.2 }, { min: 0.5, max: 30 }),
  A('ft4', 'Free T4', 'Thyroid',
    ['free t4', 'ft4', 'free thyroxine'],
    'ng/dL', { low: 0.8, high: 1.8 }, { min: 0.1, max: 8 }),

  // ---------- Vitamins & Iron ----------
  A('vitamin_d', 'Vitamin D (25-OH)', 'Vitamins & Iron',
    ['25-hydroxy vitamin d', '25 hydroxy vitamin d', '25-oh vitamin d', 'vitamin d (25-oh)', 'vitamin d total', 'vitamin d3', 'vitamin d', 'vit d'],
    'ng/mL', { low: 30, high: 100 }, { min: 1, max: 300 },
    { notes: { low: 'is extremely common; sunlight exposure and supplementation (under guidance) usually correct it' } }),
  A('vitamin_b12', 'Vitamin B12', 'Vitamins & Iron',
    ['vitamin b12', 'vitamin b-12', 'cyanocobalamin', 'cobalamin', 'vit b12', 'b12'],
    'pg/mL', { low: 200, high: 900 }, { min: 20, max: 5000 },
    { notes: { low: 'can cause fatigue and tingling; common in vegetarian diets and treatable with supplements' } }),
  A('folate', 'Folate', 'Vitamins & Iron',
    ['folic acid', 'folate', 'serum folate'],
    'ng/mL', { low: 3, high: 17 }, { min: 0.5, max: 60 }),
  A('iron', 'Iron (Serum)', 'Vitamins & Iron',
    ['serum iron', 'iron'],
    'µg/dL', { low: 60, high: 170 }, { min: 5, max: 600 }),
  A('ferritin', 'Ferritin', 'Vitamins & Iron',
    ['serum ferritin', 'ferritin'],
    'ng/mL', { low: 20, high: 250 }, { min: 1, max: 5000 }),
  A('tibc', 'TIBC', 'Vitamins & Iron',
    ['total iron binding capacity', 'tibc'],
    'µg/dL', { low: 240, high: 450 }, { min: 50, max: 800 }),
  A('transferrin_sat', 'Transferrin Saturation', 'Vitamins & Iron',
    ['transferrin saturation', '% saturation', 'tsat'],
    '%', { low: 20, high: 50 }, { min: 1, max: 100 }),

  // ---------- Hormones ----------
  A('testosterone', 'Testosterone (Total)', 'Hormones',
    ['total testosterone', 'testosterone total', 'testosterone, total', 'testosterone'],
    'ng/dL', { low: 300, high: 1000 }, { min: 5, max: 3000 }),
  A('prolactin', 'Prolactin', 'Hormones',
    ['prolactin', 'serum prolactin'],
    'ng/mL', { low: 4, high: 23 }, { min: 0.5, max: 500 }),

  // ---------- Inflammation & Cardiac ----------
  A('crp', 'CRP', 'Inflammation & Cardiac',
    ['c-reactive protein', 'c reactive protein', 'crp (quantitative)', 'crp'],
    'mg/L', { low: null, high: 6 }, { min: 0, max: 500 },
    { notes: { high: 'is a general inflammation marker - infections, injury and chronic conditions all raise it' } }),
  A('hscrp', 'hs-CRP', 'Inflammation & Cardiac',
    ['high sensitivity c-reactive protein', 'high sensitivity crp', 'hs-crp', 'hscrp'],
    'mg/L', { low: null, high: 3 }, { min: 0, max: 100 }),
  A('troponin_i', 'Troponin I', 'Inflammation & Cardiac',
    ['troponin i', 'troponin-i', 'trop i'],
    'ng/mL', { low: null, high: 0.04 }, { min: 0, max: 100 },
    { notes: { high: 'is a cardiac marker - an elevated value warrants urgent medical review' } }),
  A('ck', 'Creatine Kinase', 'Inflammation & Cardiac',
    ['creatine kinase', 'creatine phosphokinase', 'cpk', 'ck'],
    'U/L', { low: 30, high: 200 }, { min: 5, max: 50000 }),
  A('ckmb', 'CK-MB', 'Inflammation & Cardiac',
    ['ck-mb', 'ckmb'],
    'U/L', { low: null, high: 25 }, { min: 0, max: 1000 }),
  A('homocysteine', 'Homocysteine', 'Inflammation & Cardiac',
    ['homocysteine'],
    'µmol/L', { low: 5, high: 15 }, { min: 1, max: 150 }),
  A('d_dimer', 'D-Dimer', 'Inflammation & Cardiac',
    ['d-dimer', 'd dimer'],
    'ng/mL', { low: null, high: 500 }, { min: 0, max: 50000 }),

  // ---------- Pancreas & Prostate ----------
  A('amylase', 'Amylase', 'Other',
    ['serum amylase', 'amylase'],
    'U/L', { low: 30, high: 110 }, { min: 5, max: 3000 }),
  A('lipase', 'Lipase', 'Other',
    ['serum lipase', 'lipase'],
    'U/L', { low: 13, high: 60 }, { min: 2, max: 3000 }),
  A('psa', 'PSA', 'Other',
    ['prostate specific antigen', 'psa total', 'psa'],
    'ng/mL', { low: null, high: 4 }, { min: 0, max: 1000 }),

  // ---------- Coagulation ----------
  A('pt', 'Prothrombin Time', 'Coagulation',
    ['prothrombin time', 'pt'],
    'sec', { low: 11, high: 13.5 }, { min: 5, max: 120 }),
  A('inr', 'INR', 'Coagulation',
    ['international normalized ratio', 'inr'],
    'ratio', { low: 0.8, high: 1.2 }, { min: 0.3, max: 12 }),
  A('aptt', 'aPTT', 'Coagulation',
    ['activated partial thromboplastin time', 'partial thromboplastin time', 'aptt', 'ptt'],
    'sec', { low: 25, high: 35 }, { min: 10, max: 200 }),
];

// Category-level lifestyle guidance used by the insights engine when an
// analyte has no specific note. Deliberately non-diagnostic.
const CATEGORY_ADVICE = {
  'Lipid Panel': 'A heart-healthy diet, regular exercise, and weight management improve lipid numbers; discuss medication thresholds with your doctor.',
  'Diabetes': 'Blood sugar control responds to diet (lower refined carbs), activity, sleep and weight; your doctor may suggest repeat or confirmatory testing.',
  'Complete Blood Count': 'Blood count changes have many benign causes (recent illness, hydration, altitude) - trends over time matter more than one reading.',
  'Liver Function': 'Liver enzymes often normalize with reduced alcohol, weight management and medication review; persistent elevation deserves follow-up.',
  'Kidney Function': 'Kidney markers are sensitive to hydration and protein intake; persistent abnormality should be reviewed with a doctor.',
  'Electrolytes': 'Electrolyte shifts are commonly medication- or hydration-related and usually easy to correct once identified.',
  'Thyroid': 'Thyroid abnormalities are very treatable; an endocrinologist can confirm with follow-up testing before starting treatment.',
  'Vitamins & Iron': 'Deficiencies are typically corrected with diet changes or supplements - confirm dosing with your doctor.',
  'Hormones': 'Hormone levels vary by time of day and lab method; abnormal values are usually re-tested before any treatment.',
  'Inflammation & Cardiac': 'These markers are context-dependent; interpret them with your doctor alongside symptoms and history.',
  'Coagulation': 'Clotting times are medication-sensitive (especially blood thinners); report abnormal values to your prescribing doctor.',
  'Other': 'Discuss this result with your healthcare provider for context-appropriate next steps.',
};

// Units the tokenizer recognizes, longest-first at compile time.
// Scale factors normalize count-style values (7.5 x10^3 -> 7500).
const UNIT_LEXICON = [
  { re: /x?\s*10\s*[\^ eE]?\s*3\s*\/\s*[uµ]l/i, canon: 'x10³/µL', scale: 1000 },
  { re: /x?\s*10\s*[\^ eE]?\s*6\s*\/\s*[uµ]l/i, canon: 'x10⁶/µL', scale: 1 },
  { re: /thousand\s*\/\s*(cumm|cmm|[uµ]l)/i, canon: 'thousand/cumm', scale: 1000 },
  { re: /million\s*\/\s*(cumm|cmm|[uµ]l)/i, canon: 'million/cumm', scale: 1 },
  { re: /lakhs?\s*\/\s*(cumm|cmm|[uµ]l)/i, canon: 'lakh/cumm', scale: 100000 },
  { re: /cells?\s*\/\s*(cumm|cmm|[uµ]l)/i, canon: '/cumm', scale: 1 },
  { re: /\/\s*(cumm|cmm)/i, canon: '/cumm', scale: 1 },
  { re: /\/\s*[uµ]l/i, canon: '/µL', scale: 1 },
  { re: /m?i?u\s*\/\s*ml/i, canon: 'µIU/mL', scale: 1 },
  { re: /mg\s*\/\s*dl/i, canon: 'mg/dL', scale: 1 },
  { re: /g\s*\/\s*dl/i, canon: 'g/dL', scale: 1 },
  { re: /mg\s*\/\s*l/i, canon: 'mg/L', scale: 1 },
  { re: /ng\s*\/\s*ml/i, canon: 'ng/mL', scale: 1 },
  { re: /ng\s*\/\s*dl/i, canon: 'ng/dL', scale: 1 },
  { re: /pg\s*\/\s*ml/i, canon: 'pg/mL', scale: 1 },
  { re: /[uµ]g\s*\/\s*dl/i, canon: 'µg/dL', scale: 1 },
  { re: /[uµ]mol\s*\/\s*l/i, canon: 'µmol/L', scale: 1 },
  { re: /mmol\s*\/\s*l/i, canon: 'mmol/L', scale: 1 },
  { re: /nmol\s*\/\s*l/i, canon: 'nmol/L', scale: 1 },
  { re: /meq\s*\/\s*l/i, canon: 'mEq/L', scale: 1 },
  { re: /i?u\s*\/\s*l/i, canon: 'U/L', scale: 1 },
  { re: /mm\s*\/?\s*(1st\s*)?h(ou)?r/i, canon: 'mm/hr', scale: 1 },
  { re: /ml\/min\/?1?\.?7?3?m?²?/i, canon: 'mL/min/1.73m²', scale: 1 },
  { re: /sec(onds)?/i, canon: 'sec', scale: 1 },
  { re: /ratio/i, canon: 'ratio', scale: 1 },
  { re: /fl/i, canon: 'fL', scale: 1 },
  { re: /pg/i, canon: 'pg', scale: 1 },
  { re: /%/, canon: '%', scale: 1 },
];

module.exports = { ANALYTES, CATEGORY_ADVICE, UNIT_LEXICON };
